### ISSUE TITLE
download-to-cache fails, **repo file list has not been validated**

### ISSUE THREAD

**Issue by LaithZumot2** [NVIDIA/nim-deploy#51]
download-to-cache --profile someprofilehash
There was a problem when trying to write in your cache folder (/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
INFO mm-dd hh:mm:ss.sss pre_download.py:65] Downloading contents for profile someprofilehash
INFO mm-dd hh:mm:ss.sss pre_download.py:71] {
  "llm_engine": "tensorrt_llm",
  "profile": "throughput",
  "gpu_device": "2330:10de",
  "tp": "1",
  "precision": "fp16",
  "gpu": "H100",
  "feat_lora": "true",
  "feat_lora_max_rank": "32",
  "pp": "1"
}
Traceback (most recent call last):
  File "/usr/local/bin/download-to-cache", line 8, in <module>
    sys.exit(download_to_cache())
  File "/usr/local/lib/python3.10/dist-packages/vllm_nvext/hub/pre_download.py", line 75, in download_to_cache
    cached_files = repo.download_all()
Exception: "Errors fetching files: \nissue a download request for file: \"special_tokens_map.json\"; the repo file list has not been validated. \nissue a download request for file: \"config.json\"; the repo file list has not been validated. \nissue a download request for file: \"metadata.json\"; the repo file list has not been validated. \nissue a download request for file: \"rank0.engine\"; the repo file list has not been validated. \nissue a download request for file: \"trt_llm_config.yaml\"; the repo file list has not been validated. \nissue a download request for file: \"generation_config.json\"; the repo file list has not been validated. \nissue a download request for file: \"config.json\"; the repo file list has not been validated. \nissue a download request for file: \"model.safetensors.index.json\"; the repo file list has not been validated. \nissue a download request for file: \"tokenizer.json\"; the repo file list has not been validated. \nissue a download request for file: \"checksums.blake3\"; the repo file list has not been validated. \nissue a download request for file: \"tokenizer_config.json\"; the repo file list has not been validated.

attempted: adding other variations of env setting. 
export TRANSFORMERS_CACHE=/model-cache/huggingface/hub/

download-to-cache --profile someprofilehash
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:124: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO mm-dd hh:mm:ss.sss pre_download.py:65] Downloading contents for profile someprofilehash
INFO mm-dd hh:mm:ss.sss pre_download.py:71] {
  "gpu": "H100",
  "feat_lora_max_rank": "32",
  "precision": "fp16",
  "gpu_device": "2330:10de",
  "tp": "1",
  "feat_lora": "true",
  "llm_engine": "tensorrt_llm",
  "profile": "throughput",
  "pp": "1"
}
Traceback (most recent call last):
  File "/usr/local/bin/download-to-cache", line 8, in <module>
    sys.exit(download_to_cache())
  File "/usr/local/lib/python3.10/dist-packages/vllm_nvext/hub/pre_download.py", line 75, in download_to_cache
    cached_files = repo.download_all()
Exception: "Errors fetching files: \nissue a download request for file: \"special_tokens_map.json\"; the repo file list has not been validated. \nissue a download request for file: \"config.json\"; the repo file list has not been validated. \nissue a download request for file: \"trt_llm_config.yaml\"; the repo file list has not been validated. \nissue a download request for file: \"tokenizer_config.json\"; the repo file list has not been validated. \nissue a download request for file: \"generation_config.json\"; the repo file list has not been validated. \nissue a download request for file: \"rank0.engine\"; the repo file list has not been validated. \nissue a download request for file: \"checksums.blake3\"; the repo file list has not been validated. \nissue a download request for file: \"config.json\"; the repo file list has not been validated. \nissue a download request for file: \"metadata.json\"; the repo file list has not been validated. \nissue a download request for file: \"tokenizer.json\"; the repo file list has not been validated. \nissue a download request for file: \"model.safetensors.index.json\"; the repo file list has not been validated. "

**Comment by supertetelman** [comment]
Can you please provide some additional details around to deployment technique you are using, the operating system, the startup commands you may have changed, and the exact container you are using? The output of nvidia-smi and kubectl describe nodes would also be useful.

**Comment by pwschuurman** [comment]
+ I encountered this running as well, running a pod on GKE using [`g2-standard-4` (L4 GPU)](https://cloud.google.com/compute/docs/gpus#l4-gpus).

Repro steps:
1. Create a GKE cluster, with `g2-standard-4` machine shape.
2. Follow https://docs.nvidia.com/nim/large-language-models/latest/getting-started.html#launch-nvidia-nim-for-llms to setup a `ngc-api` and `registry-secret` secrets
3. Run pod with the following spec:

```
  apiVersion: v1
  kind: Pod
  metadata:
    name: my-nim
    namespace: nim
  spec:
    imagePullSecrets:
    - name: registry-secret
    containers:
    - command:
      - /bin/bash
      - -c
      - sleep 3600
      env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_CLI_API_KEY
            name: ngc-api
      - name: HF_HOME
        value: /model-store/cache
      image: nvcr.io/nim/meta/llama3-8b-instruct:1.0.0
      name: sleep
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      volumeMounts:
      - mountPath: /model-store
        name: model-store
    volumes:
    - emptyDir: {}
      name: model-store
```

4. Enter pod shell

```
kubectl exec -it my-nim -n nim -- /bin/bash
```

5. Follow https://docs.nvidia.com/nim/large-language-models/latest/getting-started.html#serving-models-from-local-assets to cache models to a local directory

```
download-to-cache
INFO 07-26 05:32:44.883 ngc_profile.py:217] Running NIM without LoRA. Only looking for compatible profiles that do not support LoRA.
INFO 07-26 05:32:44.883 ngc_profile.py:219] Detected 1 compatible profile(s).
INFO 07-26 05:32:44.883 ngc_injector.py:106] Valid profile: 8835c31752fbc67ef658b20a9f78e056914fdef0660206d82f252d62fd96064d (vllm-fp16-tp1) on GPUs [0]
INFO 07-26 05:32:44.883 pre_download.py:31] Selected profile: 8835c31752fbc67ef658b20a9f78e056914fdef0660206d82f252d62fd96064d (vllm-fp16-tp1)
INFO 07-26 05:32:44.883 pre_download.py:65] Downloading contents for profile 8835c31752fbc67ef658b20a9f78e056914fdef0660206d82f252d62fd96064d
INFO 07-26 05:32:44.883 pre_download.py:71] {
  "precision": "fp16",
  "feat_lora": "false",
  "tp": "1",
  "llm_engine": "vllm"
}
Traceback (most recent call last):
  File "/usr/local/bin/download-to-cache", line 8, in <module>
    sys.exit(download_to_cache())
  File "/usr/local/lib/python3.10/dist-packages/vllm_nvext/hub/pre_download.py", line 75, in download_to_cache
    cached_files = repo.download_all()
Exception: "Errors fetching files: \nissue a download request for file: \"model-00004-of-00004.safetensors\"; the repo file list has not been validated. \nissue a download request for file: \"model-00001-of-00004.safetensors\"; the repo file list has not been validated. \nissue a d
ownload request for file: \"config.json\"; the repo file list has not been validated. \nissue a download request for file: \"generation_config.json\"; the repo file list has not been validated. \nissue a download request for file: \"model.safetensors.index.json\"; the repo file lis
t has not been validated. \nissue a download request for file: \"tokenizer.json\"; the repo file list has not been validated. \nissue a download request for file: \"tokenizer_config.json\"; the repo file list has not been validated. \nissue a download request for file: \"model-0000
2-of-00004.safetensors\"; the repo file list has not been validated. \nissue a download request for file: \"model-00003-of-00004.safetensors\"; the repo file list has not been validated. \nissue a download request for file: \"special_tokens_map.json\"; the repo file list has not be
en validated. "
```

nvidia-smi:

```
nvidia-smi
Fri Jul 26 05:18:47 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                      Off | 00000000:00:03.0 Off |                    0 |
| N/A   49C    P8              17W /  72W |      0MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by supertetelman** [comment]
This does not appear to be an issue with any of the code in this repo, rather an issue with your NIM configuration itself. I'd recommend opening up a help ticket with NVIDIA enterprise support.

**Comment by pwschuurman** [comment]
Thanks! The following worked:

```
  apiVersion: v1
  kind: Pod
  metadata:
    name: my-nim
    namespace: nim
  spec:
    imagePullSecrets:
    - name: registry-secret
    containers:
    - command:
      - /bin/bash
      - -c
      - sleep 3600
      env:
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_CLI_API_KEY
            name: ngc-api
      - name: NIM_CACHE_PATH
        value: /.cache
      image: nvcr.io/nim/meta/llama3-8b-instruct:1.0.0
      name: sleep
      resources:
        limits:
          nvidia.com/gpu: "1"
        requests:
          nvidia.com/gpu: "1"
      volumeMounts:
      - mountPath: /.cache
        name: model-store
    volumes:
    - emptyDir: {}
      name: model-store
```
